### PR TITLE
Surgically handle managerPubkey format mismatch within operations

### PR DESCRIPTION
**Pull request by ivanopagano**
* remove the previous coarse-grained solution

### CODE REVIEW

**Comment by ivanopagano** [comment]
Might get deprecated as only `zeronet` have such discrepancy to handle, and we will probably drop support for it

**Comment by vishakh** [comment]
Closing this PR as `zeronet` is now out of scope.

**Comment by ivanopagano** [comment]
@vishakh I see that actually, a [proposed tezos upgrade](https://gitlab.com/nomadic-labs/tezos/commit/50cf26f012c456248a2a01d59e654fe9993b117b) might actually align the inconsistency we need to handle here

**Comment by ivanopagano** [comment]
May I suggest to re-open this PR?

Even though we might not need it, we do adapt the json, as our internal (conseil) choice of casing is anyway more consistent, and will probably be the same for a possible alphanet/mainnet upgrade.

The code outlined here does the same thing we're doing anyway, but it's a more clean and localized (in terms of code) solution.

@vishakh

**Pull request closed without merging**
