### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by leenpaws**

### CODE REVIEW

**Comment by vishakh** [comment]
Could you put into the description what meaningful change was made here?

**Comment by leenpaws** [comment]
> Could you put into the description what meaningful change was made here?

no meaningful change was made, this was merely to be able to deploy using jenkins

**Comment by vishakh** [comment]
> > Could you put into the description what meaningful change was made here?
> 
> no meaningful change was made, this was merely to be able to deploy using jenkins

What actually changed in this PR? All I see is some new whitespace.

**Comment by vishakh** [comment]
Hasta la vista

**Pull request closed without merging**
